version: '3.9'

services:

  db:
    image: postgres:alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo:
    image: luganodestodo/todo-service
    env_file:
      - ./.env
    environment:
      - PORT=5001
    ports:
      - "5001:5001"

  auth:
    image: luganodestodo/auth-service
    env_file:
      - ./.env
    environment:
      - PORT=4001
    ports:
      - "4001:4001"

  frontend:
    image: luganodestodo/frontend-service
    ports:
      - "3000:3000"

  nginx:
    image: luganodestodo/nginx
    ports:
      - "80:80"
    depends_on:
      - todo
      - auth
      - frontend
    links:
      - todo
      - auth
      - frontend
    
volumes:
  postgres_data: